### ISSUE TITLE
Site Change

### ISSUE THREAD

**Issue by jj777** [ArtS/28degrees-export#12]
Has something on the site changed again? With latest from git.

```
Logging in...
OK
Opening transactions page...
OK
Traceback (most recent call last):
  File "./export.py", line 317, in <module>
    export(**vars(args))
  File "./export.py", line 251, in export
    page_trans = fetchTransactions(text)
  File "./export.py", line 65, in fetchTransactions
    date = parse_tran_date(get_node_text(q('div[name="Transaction_TransactionDat
e"]', row)[0]))
  File "/home/xxxxxxx/28degrees-export/dateutil.py", line 6, in parse_tran_date
    return datetime.strptime(dateStr, f_str)
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Yesterday' does not match format '%d %b %Y'
```

**Comment by joelj7** [comment]
![strange](https://cloud.githubusercontent.com/assets/6631089/5799649/e851c1a0-a028-11e4-935e-330930c1275d.png)

**Comment by ArtS** [comment]
Interesting, I am not seeng this error. Possibly it's A/B split tested,
i.e. some users get old UI, some new. We can wait and see.

On Mon, Jan 19, 2015 at 10:17 PM, joelj7 <notifications@github.com> wrote:

> [image: strange]
> <https://cloud.githubusercontent.com/assets/6631089/5799649/e851c1a0-a028-11e4-935e-330930c1275d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtS/28degrees-export/issues/12#issuecomment-70478316>
> .
>



-- 
Art
04 1639 4620
