### ISSUE TITLE
Unable to access new transactions since November

### ISSUE THREAD

**Issue by FatBoyNotSoSlim** [ArtS/28degrees-export#13]
I've been getting 0 new transactions since mid November. I thought it corresponded with the message for a new card in the mail/activate said card etc. however still nothing new.

Output is:
```
Enter your username:
.....
Password:
Logging in...
OK
Opening transactions page...
OK
Total of 0 new transactions obtained
```
Using Python 2.7.6 on Ubuntu Server,  3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

Currently setting up a seperate system to test with.

**Comment by ArtS** [comment]
Interesting, just tested it and seems all fine.

If you want you can enable debugging logging by uncommenting lines 148
and 158 of export.py and then see what's in 1st-tran.html and 2nd-
tran.html files - should be the same (sans styling/images) as you get
when logging in in the browser.

After you get those feel free to remove any identifying info and send
them over to me so I can test them with PyQueries that script runs. It's
possible 28degs are A/B testing something and you are getting new
version of pages served and this breaks CSS queries that I use.


On Wed, Dec 16, 2015, at 08:21 PM, FatBoyNotSoSlim wrote:
> I've been getting 0 new transactions since mid November I thought it
> corresponded with the message for a new card in the mail/activate said
> card etc however still nothing new


> Output is:


> Enter your username:

Password: Logging in OK Opening transactions page OK Total of 0 new
transactions obtained
>
> Using Python 276 on Ubuntu Server,  3130-71-generic #114-Ubuntu SMP
> Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


> Currently setting up a seperate system to test with


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/ArtS/28degrees-export/issues/13

**Comment by FatBoyNotSoSlim** [comment]
Sure enough the debug output showed a blocking page for the activation of a new card. Even more odd, I had to use another computer to see this and get rid of it, as it wasn't showing on my main desktop. Once cleared, the python script worked again flawlessly.

Thanks heaps. :)

**Comment by ArtS** [comment]
Yeah, they must've changed the pages again... I have logic there to
catch the new card scenario, but it didn't work for you, so there
must've been a change. I am only going to be able to update it when my
own card expires though, or if you still have that file with card
activation request and don't mind sending it over.


On Wed, Dec 16, 2015, at 08:43 PM, FatBoyNotSoSlim wrote:
> Sure enough the debug output showed a blocking page for the activation
> of a new card. Even more odd, I had to use another computer to see
> this and get rid of it, as it wasn't showing on my main desktop. Once
> cleared, the python script worked again flawlessly.


> Thanks heaps. :)


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/ArtS/28degrees-export/issues/13#issuecomment-165049614
